// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatbuf-proto.proto

package com.uofantarctica.dsync.model;

public final class ChatbufProto {
  private ChatbufProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ChatMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.uofantarctica.dsync.model.ChatMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string to = 1;</code>
     */
    boolean hasTo();
    /**
     * <code>required string to = 1;</code>
     */
    java.lang.String getTo();
    /**
     * <code>required string to = 1;</code>
     */
    com.google.protobuf.ByteString
        getToBytes();

    /**
     * <code>required string from = 2;</code>
     */
    boolean hasFrom();
    /**
     * <code>required string from = 2;</code>
     */
    java.lang.String getFrom();
    /**
     * <code>required string from = 2;</code>
     */
    com.google.protobuf.ByteString
        getFromBytes();

    /**
     * <code>required .com.uofantarctica.dsync.model.ChatMessage.ChatMessageType type = 3 [default = CHAT];</code>
     */
    boolean hasType();
    /**
     * <code>required .com.uofantarctica.dsync.model.ChatMessage.ChatMessageType type = 3 [default = CHAT];</code>
     */
    com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.ChatMessageType getType();

    /**
     * <code>optional string data = 4;</code>
     */
    boolean hasData();
    /**
     * <code>optional string data = 4;</code>
     */
    java.lang.String getData();
    /**
     * <code>optional string data = 4;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <code>required int32 timestamp = 5;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required int32 timestamp = 5;</code>
     */
    int getTimestamp();
  }
  /**
   * Protobuf type {@code com.uofantarctica.dsync.model.ChatMessage}
   */
  public static final class ChatMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.uofantarctica.dsync.model.ChatMessage)
      ChatMessageOrBuilder {
    // Use ChatMessage.newBuilder() to construct.
    private ChatMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChatMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChatMessage defaultInstance;
    public static ChatMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ChatMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChatMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              to_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              from_ = bs;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.ChatMessageType value = com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.ChatMessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                type_ = value;
              }
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              data_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              timestamp_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.uofantarctica.dsync.model.ChatbufProto.internal_static_com_uofantarctica_dsync_model_ChatMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.uofantarctica.dsync.model.ChatbufProto.internal_static_com_uofantarctica_dsync_model_ChatMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.class, com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ChatMessage> PARSER =
        new com.google.protobuf.AbstractParser<ChatMessage>() {
      public ChatMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChatMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.uofantarctica.dsync.model.ChatMessage.ChatMessageType}
     */
    public enum ChatMessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CHAT = 0;</code>
       */
      CHAT(0, 0),
      /**
       * <code>HELLO = 1;</code>
       */
      HELLO(1, 1),
      /**
       * <code>LEAVE = 2;</code>
       */
      LEAVE(2, 2),
      /**
       * <code>JOIN = 3;</code>
       */
      JOIN(3, 3),
      /**
       * <code>OTHER = 4;</code>
       */
      OTHER(4, 4),
      ;

      /**
       * <code>CHAT = 0;</code>
       */
      public static final int CHAT_VALUE = 0;
      /**
       * <code>HELLO = 1;</code>
       */
      public static final int HELLO_VALUE = 1;
      /**
       * <code>LEAVE = 2;</code>
       */
      public static final int LEAVE_VALUE = 2;
      /**
       * <code>JOIN = 3;</code>
       */
      public static final int JOIN_VALUE = 3;
      /**
       * <code>OTHER = 4;</code>
       */
      public static final int OTHER_VALUE = 4;


      public final int getNumber() { return value; }

      public static ChatMessageType valueOf(int value) {
        switch (value) {
          case 0: return CHAT;
          case 1: return HELLO;
          case 2: return LEAVE;
          case 3: return JOIN;
          case 4: return OTHER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ChatMessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ChatMessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ChatMessageType>() {
              public ChatMessageType findValueByNumber(int number) {
                return ChatMessageType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final ChatMessageType[] VALUES = values();

      public static ChatMessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ChatMessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.uofantarctica.dsync.model.ChatMessage.ChatMessageType)
    }

    private int bitField0_;
    public static final int TO_FIELD_NUMBER = 1;
    private java.lang.Object to_;
    /**
     * <code>required string to = 1;</code>
     */
    public boolean hasTo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string to = 1;</code>
     */
    public java.lang.String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          to_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string to = 1;</code>
     */
    public com.google.protobuf.ByteString
        getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROM_FIELD_NUMBER = 2;
    private java.lang.Object from_;
    /**
     * <code>required string from = 2;</code>
     */
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string from = 2;</code>
     */
    public java.lang.String getFrom() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          from_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string from = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFromBytes() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.ChatMessageType type_;
    /**
     * <code>required .com.uofantarctica.dsync.model.ChatMessage.ChatMessageType type = 3 [default = CHAT];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .com.uofantarctica.dsync.model.ChatMessage.ChatMessageType type = 3 [default = CHAT];</code>
     */
    public com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.ChatMessageType getType() {
      return type_;
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private java.lang.Object data_;
    /**
     * <code>optional string data = 4;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string data = 4;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          data_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string data = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private int timestamp_;
    /**
     * <code>required int32 timestamp = 5;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 timestamp = 5;</code>
     */
    public int getTimestamp() {
      return timestamp_;
    }

    private void initFields() {
      to_ = "";
      from_ = "";
      type_ = com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.ChatMessageType.CHAT;
      data_ = "";
      timestamp_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFrom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getToBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFromBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDataBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getToBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFromBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDataBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.uofantarctica.dsync.model.ChatbufProto.ChatMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.uofantarctica.dsync.model.ChatbufProto.ChatMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.uofantarctica.dsync.model.ChatbufProto.ChatMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.uofantarctica.dsync.model.ChatbufProto.ChatMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.uofantarctica.dsync.model.ChatbufProto.ChatMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.uofantarctica.dsync.model.ChatbufProto.ChatMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.uofantarctica.dsync.model.ChatbufProto.ChatMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.uofantarctica.dsync.model.ChatbufProto.ChatMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.uofantarctica.dsync.model.ChatbufProto.ChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.uofantarctica.dsync.model.ChatbufProto.ChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.uofantarctica.dsync.model.ChatbufProto.ChatMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.uofantarctica.dsync.model.ChatMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.uofantarctica.dsync.model.ChatMessage)
        com.uofantarctica.dsync.model.ChatbufProto.ChatMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.uofantarctica.dsync.model.ChatbufProto.internal_static_com_uofantarctica_dsync_model_ChatMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.uofantarctica.dsync.model.ChatbufProto.internal_static_com_uofantarctica_dsync_model_ChatMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.class, com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.Builder.class);
      }

      // Construct using com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        to_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        from_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.ChatMessageType.CHAT;
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.uofantarctica.dsync.model.ChatbufProto.internal_static_com_uofantarctica_dsync_model_ChatMessage_descriptor;
      }

      public com.uofantarctica.dsync.model.ChatbufProto.ChatMessage getDefaultInstanceForType() {
        return com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.getDefaultInstance();
      }

      public com.uofantarctica.dsync.model.ChatbufProto.ChatMessage build() {
        com.uofantarctica.dsync.model.ChatbufProto.ChatMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.uofantarctica.dsync.model.ChatbufProto.ChatMessage buildPartial() {
        com.uofantarctica.dsync.model.ChatbufProto.ChatMessage result = new com.uofantarctica.dsync.model.ChatbufProto.ChatMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.to_ = to_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.from_ = from_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.uofantarctica.dsync.model.ChatbufProto.ChatMessage) {
          return mergeFrom((com.uofantarctica.dsync.model.ChatbufProto.ChatMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.uofantarctica.dsync.model.ChatbufProto.ChatMessage other) {
        if (other == com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.getDefaultInstance()) return this;
        if (other.hasTo()) {
          bitField0_ |= 0x00000001;
          to_ = other.to_;
          onChanged();
        }
        if (other.hasFrom()) {
          bitField0_ |= 0x00000002;
          from_ = other.from_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasData()) {
          bitField0_ |= 0x00000008;
          data_ = other.data_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTo()) {
          
          return false;
        }
        if (!hasFrom()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.uofantarctica.dsync.model.ChatbufProto.ChatMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.uofantarctica.dsync.model.ChatbufProto.ChatMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object to_ = "";
      /**
       * <code>required string to = 1;</code>
       */
      public boolean hasTo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string to = 1;</code>
       */
      public java.lang.String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            to_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string to = 1;</code>
       */
      public com.google.protobuf.ByteString
          getToBytes() {
        java.lang.Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string to = 1;</code>
       */
      public Builder setTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string to = 1;</code>
       */
      public Builder clearTo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      /**
       * <code>required string to = 1;</code>
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        to_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object from_ = "";
      /**
       * <code>required string from = 2;</code>
       */
      public boolean hasFrom() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string from = 2;</code>
       */
      public java.lang.String getFrom() {
        java.lang.Object ref = from_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            from_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string from = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFromBytes() {
        java.lang.Object ref = from_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          from_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string from = 2;</code>
       */
      public Builder setFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string from = 2;</code>
       */
      public Builder clearFrom() {
        bitField0_ = (bitField0_ & ~0x00000002);
        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }
      /**
       * <code>required string from = 2;</code>
       */
      public Builder setFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        from_ = value;
        onChanged();
        return this;
      }

      private com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.ChatMessageType type_ = com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.ChatMessageType.CHAT;
      /**
       * <code>required .com.uofantarctica.dsync.model.ChatMessage.ChatMessageType type = 3 [default = CHAT];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .com.uofantarctica.dsync.model.ChatMessage.ChatMessageType type = 3 [default = CHAT];</code>
       */
      public com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.ChatMessageType getType() {
        return type_;
      }
      /**
       * <code>required .com.uofantarctica.dsync.model.ChatMessage.ChatMessageType type = 3 [default = CHAT];</code>
       */
      public Builder setType(com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.ChatMessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.uofantarctica.dsync.model.ChatMessage.ChatMessageType type = 3 [default = CHAT];</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.ChatMessageType.CHAT;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>optional string data = 4;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string data = 4;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            data_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string data = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string data = 4;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 4;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 4;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        data_ = value;
        onChanged();
        return this;
      }

      private int timestamp_ ;
      /**
       * <code>required int32 timestamp = 5;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 timestamp = 5;</code>
       */
      public int getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int32 timestamp = 5;</code>
       */
      public Builder setTimestamp(int value) {
        bitField0_ |= 0x00000010;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 timestamp = 5;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.uofantarctica.dsync.model.ChatMessage)
    }

    static {
      defaultInstance = new ChatMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.uofantarctica.dsync.model.ChatMessage)
  }

  public interface ChatMessageListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.uofantarctica.dsync.model.ChatMessageList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
     */
    java.util.List<com.uofantarctica.dsync.model.ChatbufProto.ChatMessage> 
        getMessageListList();
    /**
     * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
     */
    com.uofantarctica.dsync.model.ChatbufProto.ChatMessage getMessageList(int index);
    /**
     * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
     */
    int getMessageListCount();
    /**
     * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
     */
    java.util.List<? extends com.uofantarctica.dsync.model.ChatbufProto.ChatMessageOrBuilder> 
        getMessageListOrBuilderList();
    /**
     * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
     */
    com.uofantarctica.dsync.model.ChatbufProto.ChatMessageOrBuilder getMessageListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.uofantarctica.dsync.model.ChatMessageList}
   */
  public static final class ChatMessageList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.uofantarctica.dsync.model.ChatMessageList)
      ChatMessageListOrBuilder {
    // Use ChatMessageList.newBuilder() to construct.
    private ChatMessageList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChatMessageList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChatMessageList defaultInstance;
    public static ChatMessageList getDefaultInstance() {
      return defaultInstance;
    }

    public ChatMessageList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChatMessageList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                messageList_ = new java.util.ArrayList<com.uofantarctica.dsync.model.ChatbufProto.ChatMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              messageList_.add(input.readMessage(com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          messageList_ = java.util.Collections.unmodifiableList(messageList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.uofantarctica.dsync.model.ChatbufProto.internal_static_com_uofantarctica_dsync_model_ChatMessageList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.uofantarctica.dsync.model.ChatbufProto.internal_static_com_uofantarctica_dsync_model_ChatMessageList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList.class, com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList.Builder.class);
    }

    public static com.google.protobuf.Parser<ChatMessageList> PARSER =
        new com.google.protobuf.AbstractParser<ChatMessageList>() {
      public ChatMessageList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatMessageList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChatMessageList> getParserForType() {
      return PARSER;
    }

    public static final int MESSAGELIST_FIELD_NUMBER = 1;
    private java.util.List<com.uofantarctica.dsync.model.ChatbufProto.ChatMessage> messageList_;
    /**
     * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
     */
    public java.util.List<com.uofantarctica.dsync.model.ChatbufProto.ChatMessage> getMessageListList() {
      return messageList_;
    }
    /**
     * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
     */
    public java.util.List<? extends com.uofantarctica.dsync.model.ChatbufProto.ChatMessageOrBuilder> 
        getMessageListOrBuilderList() {
      return messageList_;
    }
    /**
     * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
     */
    public int getMessageListCount() {
      return messageList_.size();
    }
    /**
     * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
     */
    public com.uofantarctica.dsync.model.ChatbufProto.ChatMessage getMessageList(int index) {
      return messageList_.get(index);
    }
    /**
     * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
     */
    public com.uofantarctica.dsync.model.ChatbufProto.ChatMessageOrBuilder getMessageListOrBuilder(
        int index) {
      return messageList_.get(index);
    }

    private void initFields() {
      messageList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getMessageListCount(); i++) {
        if (!getMessageList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < messageList_.size(); i++) {
        output.writeMessage(1, messageList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < messageList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, messageList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.uofantarctica.dsync.model.ChatMessageList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.uofantarctica.dsync.model.ChatMessageList)
        com.uofantarctica.dsync.model.ChatbufProto.ChatMessageListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.uofantarctica.dsync.model.ChatbufProto.internal_static_com_uofantarctica_dsync_model_ChatMessageList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.uofantarctica.dsync.model.ChatbufProto.internal_static_com_uofantarctica_dsync_model_ChatMessageList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList.class, com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList.Builder.class);
      }

      // Construct using com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMessageListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (messageListBuilder_ == null) {
          messageList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          messageListBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.uofantarctica.dsync.model.ChatbufProto.internal_static_com_uofantarctica_dsync_model_ChatMessageList_descriptor;
      }

      public com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList getDefaultInstanceForType() {
        return com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList.getDefaultInstance();
      }

      public com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList build() {
        com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList buildPartial() {
        com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList result = new com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList(this);
        int from_bitField0_ = bitField0_;
        if (messageListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            messageList_ = java.util.Collections.unmodifiableList(messageList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.messageList_ = messageList_;
        } else {
          result.messageList_ = messageListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList) {
          return mergeFrom((com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList other) {
        if (other == com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList.getDefaultInstance()) return this;
        if (messageListBuilder_ == null) {
          if (!other.messageList_.isEmpty()) {
            if (messageList_.isEmpty()) {
              messageList_ = other.messageList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMessageListIsMutable();
              messageList_.addAll(other.messageList_);
            }
            onChanged();
          }
        } else {
          if (!other.messageList_.isEmpty()) {
            if (messageListBuilder_.isEmpty()) {
              messageListBuilder_.dispose();
              messageListBuilder_ = null;
              messageList_ = other.messageList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              messageListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMessageListFieldBuilder() : null;
            } else {
              messageListBuilder_.addAllMessages(other.messageList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getMessageListCount(); i++) {
          if (!getMessageList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.uofantarctica.dsync.model.ChatbufProto.ChatMessageList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.uofantarctica.dsync.model.ChatbufProto.ChatMessage> messageList_ =
        java.util.Collections.emptyList();
      private void ensureMessageListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          messageList_ = new java.util.ArrayList<com.uofantarctica.dsync.model.ChatbufProto.ChatMessage>(messageList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.uofantarctica.dsync.model.ChatbufProto.ChatMessage, com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.Builder, com.uofantarctica.dsync.model.ChatbufProto.ChatMessageOrBuilder> messageListBuilder_;

      /**
       * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
       */
      public java.util.List<com.uofantarctica.dsync.model.ChatbufProto.ChatMessage> getMessageListList() {
        if (messageListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(messageList_);
        } else {
          return messageListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
       */
      public int getMessageListCount() {
        if (messageListBuilder_ == null) {
          return messageList_.size();
        } else {
          return messageListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
       */
      public com.uofantarctica.dsync.model.ChatbufProto.ChatMessage getMessageList(int index) {
        if (messageListBuilder_ == null) {
          return messageList_.get(index);
        } else {
          return messageListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
       */
      public Builder setMessageList(
          int index, com.uofantarctica.dsync.model.ChatbufProto.ChatMessage value) {
        if (messageListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageListIsMutable();
          messageList_.set(index, value);
          onChanged();
        } else {
          messageListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
       */
      public Builder setMessageList(
          int index, com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.Builder builderForValue) {
        if (messageListBuilder_ == null) {
          ensureMessageListIsMutable();
          messageList_.set(index, builderForValue.build());
          onChanged();
        } else {
          messageListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
       */
      public Builder addMessageList(com.uofantarctica.dsync.model.ChatbufProto.ChatMessage value) {
        if (messageListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageListIsMutable();
          messageList_.add(value);
          onChanged();
        } else {
          messageListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
       */
      public Builder addMessageList(
          int index, com.uofantarctica.dsync.model.ChatbufProto.ChatMessage value) {
        if (messageListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageListIsMutable();
          messageList_.add(index, value);
          onChanged();
        } else {
          messageListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
       */
      public Builder addMessageList(
          com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.Builder builderForValue) {
        if (messageListBuilder_ == null) {
          ensureMessageListIsMutable();
          messageList_.add(builderForValue.build());
          onChanged();
        } else {
          messageListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
       */
      public Builder addMessageList(
          int index, com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.Builder builderForValue) {
        if (messageListBuilder_ == null) {
          ensureMessageListIsMutable();
          messageList_.add(index, builderForValue.build());
          onChanged();
        } else {
          messageListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
       */
      public Builder addAllMessageList(
          java.lang.Iterable<? extends com.uofantarctica.dsync.model.ChatbufProto.ChatMessage> values) {
        if (messageListBuilder_ == null) {
          ensureMessageListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, messageList_);
          onChanged();
        } else {
          messageListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
       */
      public Builder clearMessageList() {
        if (messageListBuilder_ == null) {
          messageList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          messageListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
       */
      public Builder removeMessageList(int index) {
        if (messageListBuilder_ == null) {
          ensureMessageListIsMutable();
          messageList_.remove(index);
          onChanged();
        } else {
          messageListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
       */
      public com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.Builder getMessageListBuilder(
          int index) {
        return getMessageListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
       */
      public com.uofantarctica.dsync.model.ChatbufProto.ChatMessageOrBuilder getMessageListOrBuilder(
          int index) {
        if (messageListBuilder_ == null) {
          return messageList_.get(index);  } else {
          return messageListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
       */
      public java.util.List<? extends com.uofantarctica.dsync.model.ChatbufProto.ChatMessageOrBuilder> 
           getMessageListOrBuilderList() {
        if (messageListBuilder_ != null) {
          return messageListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(messageList_);
        }
      }
      /**
       * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
       */
      public com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.Builder addMessageListBuilder() {
        return getMessageListFieldBuilder().addBuilder(
            com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
       */
      public com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.Builder addMessageListBuilder(
          int index) {
        return getMessageListFieldBuilder().addBuilder(
            index, com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .com.uofantarctica.dsync.model.ChatMessage messageList = 1;</code>
       */
      public java.util.List<com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.Builder> 
           getMessageListBuilderList() {
        return getMessageListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.uofantarctica.dsync.model.ChatbufProto.ChatMessage, com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.Builder, com.uofantarctica.dsync.model.ChatbufProto.ChatMessageOrBuilder> 
          getMessageListFieldBuilder() {
        if (messageListBuilder_ == null) {
          messageListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.uofantarctica.dsync.model.ChatbufProto.ChatMessage, com.uofantarctica.dsync.model.ChatbufProto.ChatMessage.Builder, com.uofantarctica.dsync.model.ChatbufProto.ChatMessageOrBuilder>(
                  messageList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          messageList_ = null;
        }
        return messageListBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.uofantarctica.dsync.model.ChatMessageList)
    }

    static {
      defaultInstance = new ChatMessageList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.uofantarctica.dsync.model.ChatMessageList)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_uofantarctica_dsync_model_ChatMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_uofantarctica_dsync_model_ChatMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_uofantarctica_dsync_model_ChatMessageList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_uofantarctica_dsync_model_ChatMessageList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023chatbuf-proto.proto\022\035com.uofantarctica" +
      ".dsync.model\"\340\001\n\013ChatMessage\022\n\n\002to\030\001 \002(\t" +
      "\022\014\n\004from\030\002 \002(\t\022N\n\004type\030\003 \002(\0162:.com.uofan" +
      "tarctica.dsync.model.ChatMessage.ChatMes" +
      "sageType:\004CHAT\022\014\n\004data\030\004 \001(\t\022\021\n\ttimestam" +
      "p\030\005 \002(\005\"F\n\017ChatMessageType\022\010\n\004CHAT\020\000\022\t\n\005" +
      "HELLO\020\001\022\t\n\005LEAVE\020\002\022\010\n\004JOIN\020\003\022\t\n\005OTHER\020\004\"" +
      "R\n\017ChatMessageList\022?\n\013messageList\030\001 \003(\0132" +
      "*.com.uofantarctica.dsync.model.ChatMess" +
      "age"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_uofantarctica_dsync_model_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_uofantarctica_dsync_model_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_uofantarctica_dsync_model_ChatMessage_descriptor,
        new java.lang.String[] { "To", "From", "Type", "Data", "Timestamp", });
    internal_static_com_uofantarctica_dsync_model_ChatMessageList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_uofantarctica_dsync_model_ChatMessageList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_uofantarctica_dsync_model_ChatMessageList_descriptor,
        new java.lang.String[] { "MessageList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
